---

listen:
  bind_ip: localhost
  port: 8080
db:
  host: localhost
  port: 5432
  user: admin
  password: admin
  dbname: thesis
  ssl_mode: disable
cluster_amount: 500
model_file_path: _meta/model-%s.json