---

listen:
  bind_ip: localhost
  port: 8080
db:
  host: localhost
  port: 5432
  user: admin
  password: admin
  dbname: dusha
  ssl_mode: disable
cluster_amount: 2000
model_file_path: etc/model-%s.json