version: "3.7"

services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - /data/postgresql:/var/lib/postgresql
      - /data/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/pgdata
      - POSTGRES_DB=thesis